### ISSUE TITLE
Create/reverse to commands

### ISSUE THREAD

**Issue by logicaleak** [elwinar/rambler#11]
Hi :)

I needed a migration tool, so I happened to pick yours, thanks to your stackoverflow answer.
I implemented "create" and "reverse to" commands, and kindly edited the way you check consistency 
of available and applied migrations. I am actually not completely done with "reverse to" command. 
Would you be open to contributions ?

**Comment by elwinar** [comment]
Hi.

I didn't actually planned to do a `create` command, if by that you mean `create a new migration file`. I don't feel them necessary given that the files are really simple SQL files. Anyway, its just a template dump into a file… nothing really complex.

The `reverse to` command is a good idea, it may probably be more like a `goto` command so it can be used to go forward to.

Even if I didn't do anything on this project for a while, I'm open to contributions and would happily review and merge them. I would appreciate that you make different PR for each feature so I can review them independantly.

Cheers.
