### ISSUE TITLE
Release version 3.3 to cover commits since last release

### ISSUE THREAD

**Issue by shawndellysse** [elwinar/rambler#12]
As of writing this, the last release is v3.2.0 dated 2015-09-15. There have been 11 commits since then, one of which has functionality I need for some of my projects. Could you generate a v3.3.0 or v3.2.1 release so I can simplify my ansible scripts?

I looked into doing it myself as a pull request but there's not a lot of info out there on how to get this done.

**Comment by elwinar** [comment]
I will be doing it this evening (Paris time) with great pleasure.

**Comment by elwinar** [comment]
Its done (monday wasn't possible…).
I switched to XGo for the cross-compilation while I was at it, this tool is really awesome.

**Comment by shawndellysse** [comment]
Awesome! Thanks so much!
