### ISSUE TITLE
Hive support

### ISSUE THREAD

**Issue by sengelbert** [elwinar/rambler#14]
Add support for Apache Hive

**Comment by elwinar** [comment]
I'll work on this as soon as I manage some hours of free time.

However, I don't know Hive but it seems (after a quick search) that it isn't a SQL database in a strict sense, and I didn't found a driver for it.
Anyone with more knowledge than me and willing to answer questions would be welcome.
Baring that, I won't guarantee to add it quickly ^^.

**Comment by elwinar** [comment]
So, after a bit of looking around, there is no database/sql driver for Hive, so I can't add it. And I definitively don't have the time to write it myself.
