### ISSUE TITLE
make migrations table name configurable

### ISSUE THREAD

**Issue by jbub** [elwinar/rambler#16]
table name `migrations` is too common, either make it configurable or at least prefix it with something like `rambler_migrations`, thank you for a great project

**Comment by elwinar** [comment]
Great idea, I think i'll make it configurable. Unfortunately, the default will stay to prevent breaking existing setups, at least for now.

**Comment by elwinar** [comment]
Done just now, 67d05c180d92ab0b3925beca1c90f2f573807ee6. I will release it as 4.0 (as it change the driver interface, which is a breaking change).
