### ISSUE TITLE
unable to check for database state: dial tcp: lookup port=5432: no such host

### ISSUE THREAD

**Issue by raarts** [elwinar/rambler#23]
Hi,

I encountered the above error with the rambler.json below. My intention was to migrate multiple databases on multiple hosts.

```
{
    "driver": "postgresql",
    "protocol": "tcp",
    "directory": "sql",
    "port": 5432,
    "table": "migrations",
    "environments": {
        "development": {
            "host": "my.hostname.com",
            "port": 5432,
            "user": "someuser",
            "password": "xxx",
            "database": "db_template1"
        },
        "testing": {
            "host": "other.hostname.com",
            "port": 5432,
            "user": "username",
            "password": "xxx",
            "database": "db_template2"
        }
    }
}
```

**Comment by elwinar** [comment]
Hi.
Sorry for the timeout, I was pretty busy this week-end.

First guess would be that your hostname is wrong, so check for typos.

Second guess would be that the port is wrong, as others error messages found on the web seem to indicate that the postgresql driver returns the part of the connection string that it encountered the error on.

I'll try to handle #21 today, I may add a `--debug` flag that could help you.

R;

**Comment by elwinar** [comment]
So, without any activity on this since then, I'll close it. Feel free to open another issue if need be.

**Comment by elwinar** [comment]
Maybe tied to #24, maybe not.

**Comment by raarts** [comment]
In retrospect: seems even likely, given that the error message is: 

dial tcp: lookup **port=5432**: no such host. 

I now realize rambler (or the postgresql driver) thinks the string `port=5432` is actually the hostname. So it must be a parsing error somewhere.
