### ISSUE TITLE
host from rambler.json, not added to final connection string

### ISSUE THREAD

**Issue by yosefy** [elwinar/rambler#24]
also with env variable is the same

when we change port, it is affected, but host is always "localhost"

**Comment by elwinar** [comment]
Would you please give me an example file and commands to reproduce the problem exactly ? Haven't had a look yet, but everything tied to DSN can be harder to debug without an exact exemple.

**Comment by yosefy** [comment]
go get -u github.com/elwinar/rambler

then:

{
  "driver": "postgresql",
  "protocol": "tcp",
  "host": "db",
  "port": 5432,
  "user": "postgres",
  "database": "mdb",
  "directory": "migrations",
  "table": "migrations"
}

running
rambler -c migrations/rambler.json apply -a

i can't get the exact errror now but its something about 👍 
can't establish connection to localhost:5432

and if i change port to say 5430 then error changes to
can't establish connection to localhost:5430

so somehow it reads port but ignores the host i guess as i 
tried to change "db" to anything else and it stays localhost


also when on localhost , runs all good

is it good enough? or you need exact error?

thanks

**Comment by elwinar** [comment]
Good enough. Give me a little time, as I don't use postgresql myself so I need a little setup.

**Comment by elwinar** [comment]
I tried dumping the DSN used for connection, I get `user=postgres password= host=db port=5432 dbname=mdb sslmode=disable`. Seems like the host is correctly read, so I guess the problem lies elsewhere. Could it be that your host/port doesn't actually exist or is resolved to localhost by your machine ? I see no password, could the database simply reject the connection ?

**Comment by yosefy** [comment]
PING db (172.18.0.2) 56(84) bytes of data.
64 bytes from misc_db_1.misc_default (172.18.0.2): icmp_seq=1 ttl=64 time=0.138 ms
64 bytes from misc_db_1.misc_default (172.18.0.2): icmp_seq=2 ttl=64 time=0.090 ms


[root@4eec0d172e09 mdb]# cat migrations/rambler.json
{
  "driver": "postgresql",
  "protocol": "tcp",
  "host": "db",
  "port": 5432,
  "user": "postgres",
  "database": "db",
  "directory": "migrations",
  "table": "migrations"
}


# rambler -c migrations/rambler.json apply -a
unable to check for database state: dial tcp 127.0.0.1:5432: connect: connection refused

**Comment by yosefy** [comment]
ok there is PR.
come out the placement in the string matters
saw it here: https://github.com/lib/pq/issues/686

**Comment by elwinar** [comment]
****, seriously?

**Comment by yosefy** [comment]
yes :) i really don't understand why though

thanks in advance for fixing 🥇

**Comment by elwinar** [comment]
It is now fixed, I'll release it as soon as possible.

**Comment by elwinar** [comment]
Released as 4.1.4.
