### ISSUE TITLE
Support for Firebird SQL

### ISSUE THREAD

**Issue by micakovic** [elwinar/rambler#26]
Any plans on supporting Firebird SQL?

https://github.com/nakagami/firebirdsql 
works well with 
https://golang.org/pkg/database/sql/

**Comment by elwinar** [comment]
If there is a driver, I can add it. Following #24, I plan to do some dusting on the internals soon, I can take the occasion to add this. How soon would you like it available (can it wait a week) ?

**Comment by elwinar** [comment]
I've started working on it in the [firebird-support](https://github.com/elwinar/rambler/tree/firebird-support) branch. I don't use FirebirdSQL myself, so I will have a few hours to spend on getting to grips with it but it doesn't seems to complex.

**Comment by micakovic** [comment]
Hi, it sure can wait a week!

I've been using this driver with Go for Firebird SQL:

https://github.com/nakagami/firebirdsql

The driver works with database/sql: https://golang.org/pkg/database/sql/

**Comment by elwinar** [comment]
Hadn't had the time to do this yet. Sorry for the delay….

**Comment by elwinar** [comment]
So, I couldn't find the time to make firebird work, and forgot the issue. I'll have another try soon, but from memory Firebird is a bit harsh to work with compared to other databases I don't know, so I wouldn't bet on it.
