### ISSUE TITLE
Rambler exits with status 0 on apply failure

### ISSUE THREAD

**Issue by emmercm** [elwinar/rambler#27]
Example failures that exit with status 0:

```
unable to check for database state: pq: role "postgres" does not exist
```

```
unable to check for database state: dial tcp [::1]:5432: connect: connection refused
```

I would expect it to exit with a non-zero status to indicate the command failed. My primary use case for this is to ensure a Travis CI build fails when `rambler apply --all` fails.

**Comment by elwinar** [comment]
Hi.
Oversight on my part, the bootstrap was doing it correctly but not the commands.

**Comment by emmercm** [comment]
Awesome, thanks Romain!
