### ISSUE TITLE
Possible to use with just environment variables?

### ISSUE THREAD

**Issue by tuckerconnelly** [elwinar/rambler#33]
It seems rambler.json is required:

```
unable to load configuration from file: open rambler.json: no such file or directory
```

Would be nice to use only environment variables so connection settings can differ based on environment (dev, staging, production) without resorting to weird hacks :)

**Comment by elwinar** [comment]
Yep, it's now done. I won't release immediately in case I find a bug or if I have the time to add something else, but free time is in short supply, but you can test it from master already.
