### ISSUE TITLE
Implement dry-run

### ISSUE THREAD

**Issue by moxar** [elwinar/rambler#43]
Hi,

Is it possible to implement a `dry-run` feature on apply and/or reverse behavior ?
Here is an example (based on our current stack) of what would be done:

```
rambler apply -a --dry-run
15:31 info dry-run initializing database
15:31 info dry-run found x available migrations
15:31 info dry-run found y applied migrations
15:31 info dry-run z migrations to apply
15:31 info dry-run applying 2019_08_09_09_23_10.create_customer_table.sql
15:31 info dry-run applying 2019_08_09_14_05_00.create_user_table.sql
15:31 info dry-run applying 2019_08_09_14_55_00.create_role_table.sql
```

**Comment by elwinar** [comment]
This is implemented in the branch [43-dry-run](https://github.com/elwinar/rambler/tree/43-dry-run). Care to try it and give me a feedback?

**Comment by moxar** [comment]
It fits our needs. Thanks a lot.
When can we expect a new release ?

**Comment by elwinar** [comment]
v5.1.0 is released.
