### ISSUE TITLE
Support for Postgres sslmode

### ISSUE THREAD

**Issue by bharatari** [elwinar/rambler#48]
Rambler seems to hardcode the `sslmode` flag for Postgres databases to `disable` making it impossible to use it with databases that enforce TLS connections. Would it be possible to expose that value as part of rambler's JSON configuration file or environment variables?

**Comment by elwinar** [comment]
I can probably do something like that. I'll have a look at it.

**Comment by elwinar** [comment]
Would you mind testing with v5.3.0-rc0? It should have a new option `sslmode` (as a string defaulting to `disable` for backward-compatibility) that you can use to set the desired value.

**Comment by bharatari** [comment]
It's working perfectly, thank you so much!

**Comment by elwinar** [comment]
OK, releasing this then.
